export const uiText = {
  es: {
    localeLabel: 'ES',
    alternateLocaleLabel: 'EN',
    nav: {
      explore: 'Explorar círculos',
      becomeGuide: 'Soy guía',
      login: 'Ingresar',
      profile: 'Perfil',
      dashboard: 'Panel guía',
      logout: 'Cerrar sesión',
    },
    hero: {
      eyebrow: 'Círculos guiados para crecer acompañadas',
      title: 'Encuentra un círculo de mujeres que te sostenga, inspire y conecte contigo.',
      description:
        'Circular es una herramientas para que guias y mujeres se encuentren y reunan al rededor de circulos femeninos',
      primaryCta: 'Explorar círculos',
      secondaryCta: 'Conoce a las guías',
    },
    search: {
      title: 'Descubre tu próximo círculo',
      subtitle:
        'Busca por región, comuna, fecha o tipo de experiencia y encuentra un espacio que se sienta alineado contigo.',
      searchPlaceholder: 'Buscar por región, comuna, título o tipo',
      region: 'Región',
      comuna: 'Comuna',
      date: 'Fecha',
      type: 'Tipo',
      price: 'Precio',
      clear: 'Limpiar filtros',
      free: 'Gratuito',
      paid: 'Pagado',
      all: 'Todos',
      listView: 'Vista lista',
      mapView: 'Vista mapa',
      results: 'círculos disponibles',
      empty: 'No encontramos círculos con esos filtros. Prueba una búsqueda más amplia.',
      useMyLocation: 'Usar mi ubicación',
      locating: 'Buscando tu ubicación...',
      nearbyTitle: 'Círculos cerca de ti',
      nearbyFallback: 'Activa tu ubicación para ordenar los círculos por cercanía.',
      nearbySorted: 'Ordenamos el mapa según la distancia desde tu ubicación actual.',
      geolocationError:
        'No pudimos acceder a tu ubicación. Revisa los permisos del navegador y vuelve a intentarlo.',
      mapLoading: 'Estamos ubicando los círculos en el mapa...',
      mapUnavailable: 'Todavía no logramos ubicar estos círculos en el mapa.',
      noNearby: 'No encontramos círculos dentro del radio seleccionado.',
      youAreHere: 'Tú estás aquí',
      away: 'de distancia',
      radius: 'Radio',
      allRadius: 'Todo Chile',
    },
    circle: {
      join: 'Unirme al círculo',
      details: 'Ver detalle',
      upcoming: 'Próximos círculos',
      guide: 'Guía',
      duration: 'Duración',
      materials: 'Materiales',
      intention: 'Intención',
      theme: 'Tema',
      location: 'Ubicación',
      expect: 'Qué puedes esperar',
      formTitle: 'Reserva tu lugar',
      formSubtitle:
        'Completa tus datos y la guía recibirá tu intención para preparar mejor el encuentro.',
      confirmation:
        'Tu solicitud fue enviada con éxito. Pronto recibirás una confirmación por correo.',
      message: 'Mensaje o intención (opcional)',
      phone: 'Teléfono',
      name: 'Nombre',
      email: 'Correo electrónico',
      submit: 'Enviar solicitud',
    },
    guide: {
      title: 'Conoce a tu guía',
      directoryEyebrow: 'Guías en Circular',
      directoryTitle: 'Explora a todas las guías inscritas',
      directoryDescription:
        'Descubre sus historias, experiencia y los círculos que ya están compartiendo dentro de la plataforma.',
      story: 'Cómo se convirtió en guía de círculos',
      experience: 'Experiencia',
      special: 'Qué hace especiales sus círculos',
      reviews: 'Reseñas',
      circles: 'Círculos de esta guía',
      rating: 'Calificación',
      viewProfile: 'Ver perfil',
    },
    auth: {
      title: 'Bienvenida a Circular',
      subtitle:
        'Crea tu cuenta o inicia sesión para unirte a círculos, guardar tus datos y, si eres guía, publicar nuevas experiencias.',
      login: 'Ingresar',
      signup: 'Crear cuenta',
      password: 'Contraseña',
      role: 'Quiero entrar como',
      participant: 'Participante',
      guide: 'Guía',
      submitLogin: 'Entrar a mi cuenta',
      submitSignup: 'Crear mi cuenta',
      orContinueWith: 'o continúa con',
      googleContinue: 'Continuar con Google',
      googleLoading: 'Conectando con Google...',
      googleRoleHint: 'Si es tu primera vez, crearemos tu cuenta como {role}.',
      googleError: 'No pudimos iniciar el acceso con Google. Inténtalo nuevamente.',
      successSignup: 'Tu cuenta fue creada y ya puedes explorar Circular.',
      invalidLogin: 'No encontramos una cuenta con ese correo y contraseña.',
      existingAccount: 'Ya existe una cuenta con ese correo.',
      rateLimitError:
        'Supabase bloqueo temporalmente el envio de correos de confirmacion. Para seguir creando cuentas ahora mismo, desactiva "Confirm email" en Supabase > Authentication > Providers > Email y vuelve a intentarlo.',
      networkError:
        'No pudimos conectar con Supabase. Revisa tu conexion o la configuracion del proyecto e intentalo nuevamente.',
    },
    dashboard: {
      title: 'Panel de guía',
      subtitle:
        'Crea nuevos círculos y administra tus próximas experiencias desde un solo lugar.',
      create: 'Crear círculo',
      createSubtitle: 'Publica un nuevo encuentro en pocos pasos.',
      myCircles: 'Mis círculos publicados',
      incomingRequests: 'Solicitudes recibidas',
      requestsByEvent: 'Solicitudes por evento',
      noRequests: 'Aún no has recibido solicitudes para tus círculos.',
      noEvents: 'Todavía no has publicado eventos.',
      eventDate: 'Fecha',
      attendees: 'Solicitudes',
      applicantMessage: 'Intención compartida',
      contact: 'Contacto',
      requestsSummary: 'Revisa quién quiere sumarse a cada círculo.',
      description: 'Descripción breve',
      imageUpload: 'Subir imagen del círculo',
      imageHelp: 'Formatos permitidos: PNG, JPG, JPEG o WEBP.',
      noGuide:
        'Esta sección está disponible para cuentas guía. Crea una cuenta guía o inicia sesión con una existente.',
      success: 'Tu nuevo círculo ya está publicado en Circular.',
    },
    profile: {
      title: 'Tu perfil',
      upcoming: 'Tus próximas reservas',
      noReservations: 'Aún no tienes reservas registradas.',
      viewEvent: 'Ver evento',
      roleLabels: {
        participant: 'Participante',
        guide: 'Guía',
      },
    },
    becomeGuide: {
      title: 'Conviértete en guía en Circular',
      description:
        'Comparte tu enfoque, atrae a mujeres alineadas con tu propuesta y presenta tus círculos a la comunidad.',
      bullets: [
        'Muestra tu historia y experiencia.',
        'Publica círculos con fechas, ubicación, valor y cupos claros.',
        'Genera confianza con un perfil cálido y humano.',
      ],
      cta: 'Crear cuenta guía',
    },
    footer:
    'contacto.circular.mujeres@gmail.com',
    donation: {
      title: 'Apoya a Circular',
      description:
        'Hola, yo soy Coni, cree y mantengo circular para facilitar el encuentro de mujeres en círculos. Si este proyecto resuena contigo, haz un aporte y ayuda a mantenerlo vivo.',
      cta: 'Donar con PayPal',
    },
  },
  en: {
    localeLabel: 'EN',
    alternateLocaleLabel: 'ES',
    nav: {
      explore: 'Explore circles',
      becomeGuide: 'Be a guide',
      login: 'Login',
      profile: 'Profile',
      dashboard: 'Guide dashboard',
      logout: 'Logout',
    },
    hero: {
      eyebrow: 'Guided circles for women',
      title: 'Find a women’s circle that feels grounding, inspiring, and safe.',
      description:
        'Circular brings together intimate, professionally guided experiences around healing, creativity, spirituality, and meaningful connection.',
      primaryCta: 'Explore circles',
      secondaryCta: 'Meet the guides',
    },
    search: {
      title: 'Discover your next circle',
      subtitle:
        'Search by region, district, date, or experience type to find a circle that matches what you need.',
      searchPlaceholder: 'Search by region, district, title, or type',
      region: 'Region',
      comuna: 'District',
      date: 'Date',
      type: 'Type',
      price: 'Price',
      clear: 'Clear filters',
      free: 'Free',
      paid: 'Paid',
      all: 'All',
      listView: 'List view',
      mapView: 'Map view',
      results: 'circles available',
      empty: 'No circles match those filters yet. Try broadening your search.',
      useMyLocation: 'Use my location',
      locating: 'Finding your location...',
      nearbyTitle: 'Circles near you',
      nearbyFallback: 'Enable your location to sort circles by distance.',
      nearbySorted: 'We sort the map by distance from your current location.',
      geolocationError:
        'We could not access your location. Check your browser permissions and try again.',
      mapLoading: 'We are placing circles on the map...',
      mapUnavailable: 'We could not place these circles on the map yet.',
      noNearby: 'No circles were found within the selected radius.',
      youAreHere: 'You are here',
      away: 'away',
      radius: 'Radius',
      allRadius: 'All Chile',
    },
    circle: {
      join: 'Join circle',
      details: 'View details',
      upcoming: 'Upcoming circles',
      guide: 'Guide',
      duration: 'Duration',
      materials: 'Materials',
      intention: 'Intention',
      theme: 'Theme',
      location: 'Location',
      expect: 'What to expect',
      formTitle: 'Reserve your spot',
      formSubtitle:
        'Complete your details and the guide will receive your intention before the gathering.',
      confirmation:
        'Your request was sent successfully. You will receive a confirmation email soon.',
      message: 'Message or intention (optional)',
      phone: 'Phone',
      name: 'Name',
      email: 'Email',
      submit: 'Send request',
    },
    guide: {
      title: 'Meet your guide',
      directoryEyebrow: 'Guides on Circular',
      directoryTitle: 'Explore every guide on the platform',
      directoryDescription:
        'Discover their stories, experience, and the circles they are already sharing through Circular.',
      story: 'How she became a circle guide',
      experience: 'Experience',
      special: 'What makes her circles special',
      reviews: 'Reviews',
      circles: 'Circles by this guide',
      rating: 'Rating',
      viewProfile: 'View profile',
    },
    auth: {
      title: 'Welcome to Circular',
      subtitle:
        'Create an account or log in to join circles, save your details, and publish experiences if you are a guide.',
      login: 'Login',
      signup: 'Sign up',
      password: 'Password',
      role: 'I want to join as',
      participant: 'Participant',
      guide: 'Guide',
      submitLogin: 'Login to my account',
      submitSignup: 'Create my account',
      orContinueWith: 'or continue with',
      googleContinue: 'Continue with Google',
      googleLoading: 'Connecting to Google...',
      googleRoleHint: 'If this is your first time, we will create your account as {role}.',
      googleError: 'We could not start Google sign-in. Please try again.',
      successSignup: 'Your account was created and you can now explore Circular.',
      invalidLogin: 'We could not find an account with that email and password.',
      existingAccount: 'An account with that email already exists.',
      rateLimitError:
        'Supabase temporarily blocked confirmation emails. To keep creating accounts right now, disable "Confirm email" in Supabase > Authentication > Providers > Email and try again.',
      networkError:
        'We could not connect to Supabase. Check your connection or project configuration and try again.',
    },
    dashboard: {
      title: 'Guide dashboard',
      subtitle:
        'Create new circles and manage your upcoming experiences from one place.',
      create: 'Create circle',
      createSubtitle: 'Publish a new gathering in a few steps.',
      myCircles: 'My published circles',
      incomingRequests: 'Incoming requests',
      requestsByEvent: 'Requests by event',
      noRequests: 'You have not received any requests for your circles yet.',
      noEvents: 'You have not published any events yet.',
      eventDate: 'Date',
      attendees: 'Requests',
      applicantMessage: 'Shared intention',
      contact: 'Contact',
      requestsSummary: 'Review who wants to join each circle.',
      description: 'Short description',
      imageUpload: 'Upload circle image',
      imageHelp: 'Allowed formats: PNG, JPG, JPEG, or WEBP.',
      noGuide:
        'This area is available for guide accounts. Create a guide account or log in with one.',
      success: 'Your new circle is now published on Circular.',
    },
    profile: {
      title: 'Your profile',
      upcoming: 'Your upcoming bookings',
      noReservations: 'You do not have any bookings yet.',
      viewEvent: 'View event',
      roleLabels: {
        participant: 'Participant',
        guide: 'Guide',
      },
    },
    becomeGuide: {
      title: 'Become a guide on Circular',
      description:
        'Share your approach, attract aligned women, and present your circles in a warm, trustworthy, startup-quality experience.',
      bullets: [
        'Show your story and expertise with a professional profile.',
        'Publish circles with clear dates, location, value, and format.',
        'Build trust through a feminine, elegant, and human brand presence.',
      ],
      cta: 'Create guide account',
    },
    footer:
      'For contact or technical issues: contacto.circular.mujeres@gmail.com',
    donation: {
      title: 'Support Circular',
      description:
        'Hi my name is Coni, I created and maintain Circular to facilitate the finding of women in circles. If this project resonates with you, make a donation and help keep this project alive.',
      cta: 'Donate with PayPal',
    },
  },
}

export const circleTypeOptions = [
  { value: '', labelEs: 'Todos los tipos', labelEn: 'All types' },
  { value: 'sanacion', labelEs: 'Sanación', labelEn: 'Healing' },
  { value: 'creatividad', labelEs: 'Creatividad', labelEn: 'Creativity' },
  { value: 'espiritualidad', labelEs: 'Espiritualidad', labelEn: 'Spirituality' },
  { value: 'conexion', labelEs: 'Conexión humana', labelEn: 'Connection' },
]

export const priceOptions = [
  { value: '', labelEs: 'Todos los precios', labelEn: 'All prices' },
  { value: 'free', labelEs: 'Gratuito', labelEn: 'Free' },
  { value: 'paid', labelEs: 'Pagado', labelEn: 'Paid' },
]
